country_dict = {
        "AW": "Aruba",
        "AF": "Afeganistão",
        "AO": "Angola",
        "AI": "Anguilla",
        "AL": "Albânia",
        "AD": "Andorra",
        "AE": "Emirados árabes Unidos",
        "AR": "Argentina",
        "AM": "Arménia",
        "AS": "Samoa Americana",
        "AQ": "Antártida",
        "TF": "Terras Austrais e Antárticas Francesas",
        "AG": "Antígua e Barbuda",
        "AT": "Austria",
        "AU": "Austrália",
        "AZ": "Azerbaijão",
        "BI": "Burundi",
        "BE": "Bélgica",
        "BJ": "Benim",
        "BQ": "Países Baixos Caribenhos",
        "BF": "Burkina Faso",
        "BD": "Bangladesh",
        "BG": "Bulgária",
        "BH": "Bahrein",
        "BS": "Bahamas",
        "BA": "Bósnia e Herzegovina",
        "BL": "São Bartolomeu",
        "BY": "Bielorrússia",
        "BZ": "Belize",
        "BM": "Bermudas",
        "BO": "Bolívia",
        "BR": "Brasil",
        "BB": "Barbados",
        "BN": "Brunei",
        "BT": "Butão",
        "BW": "Botswana",
        "CF": "República Centro-áfricana",
        "CA": "Canadá",
        "CC": "Ilhas Cocos",
        "CH": "Suíça",
        "CL": "Chile",
        "CN": "China",
        "CI": "Costa do Marfim",
        "CM": "Camarões",
        "CD": "República Democrática do Congo",
        "CG": "República do Congo",
        "CK": "Ilhas Cook",
        "CO": "Colômbia",
        "KM": "Comores",
        "CV": "Cabo Verde",
        "CR": "Costa Rica",
        "CU": "Cuba",
        "CW": "Curaçao",
        "CX": "Ilha Christmas",
        "KY": "Ilhas Cayman",
        "CY": "Chipre",
        "CZ": "Tchéquia",
        "DE": "Alemanha",
        "DJ": "Djibouti",
        "DM": "Dominique",
        "DK": "Dinamarca",
        "DO": "República Dominicana",
        "DZ": "Argélia",
        "EC": "Equador",
        "EG": "Egito",
        "ER": "Eritreia",
        "EH": "República Democrática árabe Saariana",
        "ES": "Espanha",
        "EE": "Estónia",
        "ET": "Etiópia",
        "FI": "Finlândia",
        "FJ": "Fiji",
        "FK": "Ilhas Malvinas",
        "FR": "França",
        "FO": "Ilhas Feroé",
        "FM": "Micronésia",
        "GA": "Gabão",
        "GB": "Reino Unido",
        "GE": "Geórgia",
        "GG": "Guernsey",
        "GH": "Gana",
        "GI": "Gibraltar",
        "GN": "Guiné",
        "GP": "Guadalupe",
        "GM": "Gâmbia",
        "GW": "Guiné-Bissau",
        "GQ": "Guiné Equatorial",
        "GR": "Grécia",
        "GD": "Grenada",
        "GL": "Groelândia",
        "GT": "Guatemala",
        "GF": "Guiana Francesa",
        "GU": "Guam",
        "GY": "Guiana",
        "HK": "Hong Kong",
        "HN": "Honduras",
        "HR": "Croácia",
        "HT": "Haití",
        "HU": "Hungria",
        "ID": "Indonesia",
        "IM": "Ilha de Man",
        "IN": "índia",
        "IO": "Território Britânico do Oceano índico",
        "IE": "Irlanda",
        "IR": "Irão",
        "IQ": "Iraque",
        "IL": "Israel",
        "IS": "Islândia",
        "IT": "Itália",
        "JM": "Jamaïca",
        "JE": "Jersey",
        "JO": "Jordânia",
        "JP": "Japão",
        "KZ": "Cazaquistão",
        "KE": "Quênia",
        "KG": "Quirguistão",
        "KH": "Camboja",
        "KI": "Kiribati",
        "KN": "São Cristóvão e Nevis",
        "KR": "Coreia do Sul",
        "KW": "Kuwait",
        "LA": "Laos",
        "LB": "Líbano",
        "LR": "Libéria",
        "LY": "Líbia",
        "LC": "Santa Lúcia",
        "LI": "Liechtenstein",
        "LK": "Sri Lanka",
        "LS": "Lesoto",
        "LT": "Lituânia",
        "LU": "Luxemburgo",
        "LV": "Letónia",
        "MO": "Macau",
        "MF": "São Martinho",
        "MA": "Marrocos",
        "MC": "Monaco",
        "MD": "Moldávia",
        "MG": "Madagáscar",
        "MV": "Maldivas",
        "MX": "México",
        "MH": "Ilhas Marshall",
        "MK": "Macedónia",
        "ML": "Mali",
        "MT": "Malta",
        "MM": "Mianmar",
        "ME": "Montenegro",
        "MN": "Mongólia",
        "MP": "Ilhas Marianas Setentrionais",
        "MZ": "Moçambique",
        "MR": "Mauritanie",
        "MS": "Montserrat",
        "MQ": "Martinica",
        "MU": "Maurícia",
        "MW": "Malawi",
        "MY": "Malásia",
        "YT": "Maiote",
        "NA": "Namíbia",
        "NC": "Nova Caledónia",
        "NE": "Níger",
        "NF": "Ilha Norfolk",
        "NG": "Nígeria",
        "NI": "Nicarágua",
        "NU": "Niue",
        "NL": "Países Baixos",
        "NO": "Noruega",
        "NP": "Nepal",
        "NR": "Nauru",
        "NZ": "Nova Zelândia",
        "OM": "Omã",
        "PK": "Paquistão",
        "PA": "Panama",
        "PN": "Ilhas Pitcairn",
        "PE": "Perú",
        "PH": "Filipinas",
        "PW": "Palau",
        "PG": "Papua-Nova Guiné",
        "PL": "Polónia",
        "PR": "Puerto Rico",
        "KP": "Coreia do Norte",
        "PT": "Portugal",
        "PY": "Paraguai",
        "PS": "Palestina",
        "PF": "Polinésia Francesa",
        "QA": "Catar",
        "RE": "Reunião",
        "RO": "Roménia",
        "RU": "Rússia",
        "RW": "Ruanda",
        "SA": "Arábia Saudita",
        "SD": "Sudão",
        "SN": "Senega",
        "SG": "Singapura",
        "GS": "Ilhas Geórgia e Sandwich do Sul",
        "SH": "Santa Helena, Ascensão e Tristão da Cunha",
        "SB": "Ilhas Salomão",
        "SL": "Serra Leoa",
        "SV": "El Salvador",
        "SM": "San Marino",
        "SO": "Somália",
        "PM": "São Pedro e Miquelão",
        "RS": "Sérvia",
        "SS": "Sudão do Sul",
        "ST": "São Tomé e Príncipe",
        "SR": "Suriname",
        "SK": "Eslováquia",
        "SI": "Eslovênia",
        "SE": "Suécia",
        "SZ": "eSwatani",
        "SX": "Sint-Maarten",
        "SC": "Seicheles",
        "SY": "Síria",
        "TC": "Ilhas Turcas e Caicos",
        "TD": "Chade",
        "TG": "Togo",
        "TH": "Tailândia",
        "TJ": "Tajiquistão",
        "TK": "Tokelau",
        "TL": "Timor-Leste",
        "TM": "Turquemenistão",
        "TO": "Tonga",
        "TT": "Trindade e Tobag",
        "TN": "Tunísia",
        "TR": "Turquía",
        "TV": "Tuvalu",
        "TW": "Taiwan",
        "TZ": "Tanzânia",
        "UG": "Uganda",
        "UA": "Ucrânia",
        "UY": "Uruguai",
        "US": "Estados Unidos",
        "UZ": "Uzbequistão",
        "VA": "Vaticano",
        "VC": "São Vicente e Granadinas",
        "VE": "Venezuela",
        "VG": "Ilhas Virgens Britânicas",
        "VI": "Ilhas Virgens dos Estados Unidos",
        "VN": "Vietnã",
        "VU": "Vanuatu",
        "WF": "Wallis e Futuna",
        "WS": "Samoa",
        "XK": "Kosovo",
        "YE": "Iémen",
        "ZA": "áfrica do Sul",
        "ZM": "Zâmbia",
        "ZW": "Zimbabwe",
    }

def translate_country_codes(country_codes):
    
    country_names = []
    for code in country_codes:
        if code in country_dict:
            country_names.append(country_dict[code])
        else:
            country_names.append("")
    return country_names

federation_unity_dict = {
        "AC": "Acre",
        "AL": "Alagoas",
        "AP": "Amapá",
        "AM": "Amazonas",
        "BA": "Bahia",
        "CE": "Ceará",
        "DF": "Distrito Federal",
        "ES": "Espírito Santo",
        "GO": "Goiás",
        "MA": "Maranhão",
        "MT": "Mato Grosso",
        "MS": "Mato Grosso do Sul",
        "MG": "Minas Gerais",
        "PA": "Pará",
        "PB": "Paraíba",
        "PR": "Paraná",
        "PE": "Pernambuco",
        "PI": "Piauí",
        "RJ": "Rio de Janeiro",
        "RN": "Rio Grande do Norte",
        "RS": "Rio Grande do Sul",
        "RO": "Rondônia",
        "RR": "Roraima",
        "SC": "Santa Catarina",
        "SP": "São Paulo",
        "SE": "Sergipe",
        "TO": "Tocantins"
    }

def translate_federation_unity_codes(federation_unity_codes):
    
    federation_unity_names = []
    for code in federation_unity_codes:
        if code in federation_unity_dict:
            federation_unity_names.append(federation_unity_dict[code])
        else:
            federation_unity_names.append("")
    return federation_unity_names